PUT http://localhost:3001/api/products/62bf5100dd535a54e02b5730
Content-Type: application/json

  {
    "name": "Xbox Series S - updated",
    "description":
      "includes: Xbox Series S console, one Xbox Wireless Controller, a high-speed HDMI cable, power cable, and 2 AA batteries.",
    "price": 279.99
  }

